buildscript {
  repositories {
    mavenCentral()
    google()
  }
  dependencies {
    classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22'
  }
}
apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
  namespace = "com.starxh.beatoraja"
  compileSdk = 36
  sourceSets {
    main {
      manifest.srcFile 'AndroidManifest.xml'
      java.setSrcDirs(['src/main/java'])
      aidl.setSrcDirs(['src/main/java'])
      renderscript.setSrcDirs(['src/main/java'])
      res.setSrcDirs(['res'])
      assets.setSrcDirs(['assets'])
      jniLibs.setSrcDirs(['libs'])
    }
  }
  packagingOptions {
    resources {
      excludes += ['META-INF/robovm/ios/robovm.xml', 'META-INF/DEPENDENCIES.txt', 'META-INF/DEPENDENCIES',
                   'META-INF/dependencies.txt', '**/*.gwt.xml',]

      pickFirsts += ['META-INF/LICENSE.txt', 'META-INF/LICENSE', 'META-INF/license.txt', 'META-INF/LGPL2.1',
                     'META-INF/NOTICE.txt', 'META-INF/NOTICE', 'META-INF/notice.txt', 'META-INF/native-image/**']
    }
  }
  defaultConfig {
    applicationId 'com.starxh.beatoraja'
    minSdkVersion 21
    targetSdkVersion 36
    versionCode 1
    versionName "2.0"

    resConfigs "en", "zh"
  }
  compileOptions {
    sourceCompatibility "17"
    targetCompatibility "17"
    coreLibraryDesugaringEnabled = true
  }
  kotlinOptions {
    jvmTarget = '17'
  }
  composeOptions {
    kotlinCompilerExtensionVersion = "1.5.10"
  }
  buildTypes {
    release {
      minifyEnabled true
      shrinkResources true
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }
}

repositories {

  google()
}

configurations { natives }

dependencies {
  implementation 'androidx.core:core-ktx:1.9.0'
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
  implementation "com.badlogicgames.gdx-controllers:gdx-controllers-android:$gdxControllersVersion"
  implementation "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
  implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.2'
  implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
  implementation (project(':core')) {
    exclude group: 'org.xerial', module: 'sqlite-jdbc'
  }
  implementation 'org.sqldroid:sqldroid:1.0.3'
  implementation "com.badlogicgames.gdx-video:gdx-video-android:$gdxVideoVersion"

  // Compose BOM
  def composeBom = platform('androidx.compose:compose-bom:2023.06.01')
  implementation composeBom
  androidTestImplementation composeBom

  // Compose UI
  implementation 'androidx.compose.ui:ui'
  implementation 'androidx.compose.ui:ui-graphics'
  implementation 'androidx.compose.ui:ui-tooling-preview'
  implementation 'androidx.compose.material3:material3'
  implementation 'androidx.compose.material:material-icons-extended'
  implementation 'androidx.activity:activity-compose:1.8.2'
  implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0'
  implementation 'androidx.navigation:navigation-compose:2.7.7'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0'

  // Debug
  debugImplementation 'androidx.compose.ui:ui-tooling'
  debugImplementation 'androidx.compose.ui:ui-test-manifest'


  natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-arm64-v8a"
  natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-armeabi-v7a"
  natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
  natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"

}

// Called every time gradle gets executed, takes the native dependencies of
// the natives configuration, and extracts them to the proper libs/ folders
// so they get packed with the APK.
tasks.register('copyAndroidNatives') {
  doFirst {
    file("libs/armeabi-v7a/").mkdirs()
    file("libs/arm64-v8a/").mkdirs()
    file("libs/x86_64/").mkdirs()
    file("libs/x86/").mkdirs()

    configurations.natives.copy().files.each { jar ->
      def outputDir = null
      if(jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("libs/armeabi-v7a")
      if(jar.name.endsWith("natives-arm64-v8a.jar")) outputDir = file("libs/arm64-v8a")
      if(outputDir != null) {
        copy {
          from zipTree(jar)
          into outputDir
          include "*.so"
        }
      }
    }
  }
}

tasks.matching { it.name.contains("merge") && it.name.contains("JniLibFolders") }.configureEach { packageTask ->
  packageTask.dependsOn 'copyAndroidNatives'
}

tasks.register('run', Exec) {
  def path
  def localProperties = project.file("../local.properties")
  if (localProperties.exists()) {
    Properties properties = new Properties()
    localProperties.withInputStream { instr ->
      properties.load(instr)
    }
    def sdkDir = properties.getProperty('sdk.dir')
    if (sdkDir) {
      path = sdkDir
    } else {
      path = "$System.env.ANDROID_SDK_ROOT"
    }
  } else {
    path = "$System.env.ANDROID_SDK_ROOT"
  }

  def adb = path + "/platform-tools/adb"
  commandLine "$adb", 'shell', 'am', 'start', '-n', 'com.starxh.beatoraja/com.starxh.beatoraja.android.AndroidLauncher'
}

eclipse.project.name = appName + "-android"
